### ISSUE TITLE
IPTables not supported

### ISSUE THREAD

**Issue by air101** [WillyXJ/facileManager#293]
Hello again,

thank you for fixing the firewall issue, I can access the firewall tab now. But on an updated Debian 8 (Jessie) the firewall module tells me this while Installation:

iptables 1.4.21 is not supported.

Which install is supported with debian? Or which fw can I use on Debian and is supported within fmFirewall.

Thanks again!

**Comment by WillyXJ** [comment]
iptables is supported so something is wrong with the version check sequence in your environment.  On your client, could you please edit /usr/local/facileManager/fmFirewalll/functions.php and change line 223

```	$url = $serverhost . '/buildconf';```

to 

```	$url = $serverhost . '/buildconf.php';```

Then try the installer again and report back.

**Comment by air101** [comment]
Ok, I edited the file but it still says "not supported"

**Comment by WillyXJ** [comment]
What OS/distro are you using for your fM server?  Running through the fmFirewall client installer on debian 8 worked fine against an EL 6.7 fM server.  The iptables version is fine, but it's failing with a check against the server for some reason.

**Comment by WillyXJ** [comment]
Digging further into the check, the versionCheck() function in /usr/local/facileManager/fmFirewall/functions.php was put in place for future support in case the version actually mattered for particular functionality.  You could bypass the check altogether by editing /usr/local/facileManager/fmFirewall/functions.php and putting the following right after line 223:

```return true;```

This should get you through the rest of the install and fmFirewall operational.

**Comment by air101** [comment]
I will check it out in a bit. Server and Client are:
cat /proc/version
Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29)

Latest Debian with all Updates

**Comment by air101** [comment]
Ok, Installation worked but the clients are not added in the firewall list @ webinterface. When I manually add them, it says -> Client Install Required

**Comment by WillyXJ** [comment]
Confirmed bug in that fmFirewall clients are not actually getting added to the database.  Working on a solution.

**Comment by WillyXJ** [comment]
Issue fixed in fmFirewall v1.2.4.  Thanks for the report!

In your case, just reinstall the client and you should be all set.

**Comment by air101** [comment]
Good Job :+1:  Through there is still an issue. The Servers are added @ servers list successfully and I can edit everything fine through the webui. But the iptables file is not written/updated on the servers. php fw.php cron tells me "There are no files to save. Aborting."
