### ISSUE TITLE
Application wont load after login.

### ISSUE THREAD

**Issue by aredan** [WillyXJ/facileManager#353]
Suddenly facileManager stop working, I think the problem started just after upgrading my Debian server.

I don't have any error message, at least in the apache logs. The first step was an upgrade to the core and the process of upgrading the DB just happened fine but I don't get the management portal.

One thing is that every time that a login it accepts the admin credential but it keeps loading, its weird that at the same moment my pihole.log shows some dns resolutions for the facilemanager domain.

![2016-10-02 20_07_15-start](https://cloud.githubusercontent.com/assets/939894/19024880/ca2fe1e6-88db-11e6-8af0-812749620517.jpg)

Right now I'm running the 3.0-alpha.

**Comment by bigwillystyle42** [comment]
We've started seeing the same recently, and we're also running Debian. We saw the issue using v1.3.3 on September 22nd. Spent some time debugging it but got nowhere. The next morning it worked fine. 

It's now not working again, and we've upgraded to v2.2.

**Comment by bigwillystyle42** [comment]
I was able to narrow the hang down to a call to `getPostData()` in `fm-modules/facileManager/functions.php` before it started working again. I added the following line just above the call to `curl_exec()` to try and capture what URLs the program was trying to access:

`file_put_contents("/tmp/asdf",$url."\n", FILE_APPEND );`

**Comment by aredan** [comment]
It just started working again.

I managed to upgrade the clients but now when I submit a change to a zone i'm getting this error:

![2016-10-02 22_36_12-forward zones facilemanager](https://cloud.githubusercontent.com/assets/939894/19026192/becf7b80-88f0-11e6-8248-d7c8c26d2d74.jpg)

my fm.log shows a successfully update of the zone:

![2016-10-02 22_36_43-start](https://cloud.githubusercontent.com/assets/939894/19026202/d89ce3ea-88f0-11e6-8fe8-31c18cd4b74d.jpg)

but the changes are pending in the dashboard.

**Comment by lchanouha** [comment]
I experienced same behavior.
Maybe it is linked with this ? http://stackoverflow.com/questions/252907/why-does-session-start-cause-a-timeout-when-one-script-calls-another-script-usin

**Comment by WillyXJ** [comment]
I was finally able to reproduce this as it seems to be intermittent.  When the dashboard would not load, I updated my database to disable the software update check.  Then I refreshed the page and it came up as normal.  Just to verify, I enabled software updates again and the problem returned.  Until a fix is found, you can disable software updates via the UI (if you can get in) or by running the following against your database:

```
UPDATE `fm_options` SET `option_value` = '0' WHERE `fm_options`.`option_name` = 'software_update';
```

This problem (and solution) applies to all versions of fM.

**Comment by aredan** [comment]
Thank you Jon.
 I disabled it in the Admin settings and it stopped hanging at the login. 

Could this issue be because I was using an ads dns-blackhole software (pihole in this case) ??.

**Comment by WillyXJ** [comment]
The software update check performs a POST to www.facilemanager.com/check/ via PHP cURL and this POST is hanging.  After performing a CLI cURL test, the request hangs as well.  However, performing a GET against the same URL works just fine.  Therefore, while I have a support case opened with the hosting provider, the fM software update check has been changed to perform a GET.  This will be available in the next release of fM.

You can also manually apply the commit (31eed8a) to your installation if you do not want to wait for the release.

**Comment by aredan** [comment]
I found out that fmHelp isn't working too.
if I remember correctly, this used to bring some detailed help about the module in use.

![2016-10-05 09_51_15-](https://cloud.githubusercontent.com/assets/939894/19115953/dfd5d2aa-8ae1-11e6-8da0-ff18df81dde8.png)

**Comment by WillyXJ** [comment]
I think that's a separate issue with fmHelp.  However, I'm not yet able to reproduce it.  Could you please open a separate issue on that and provide any apache or php errors?

**Comment by WillyXJ** [comment]
The hangup issue has been resolved in fM v.2.3.3 for the stable users.  Anybody using the 3.0 pre-releases, the fix will be in the next alpha.

**Comment by mrgavinconway001** [comment]
This issue still exists in version 2.3.3 installed fresh on CentOS.

**Comment by WillyXJ** [comment]
It seems to have recently broken with my web host again.  Re-opening.

**Comment by WillyXJ** [comment]
I believe this issue is no longer present.
